name: notely
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0

  #firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_crashlytics: ^5.0.1

  #routing
  go_router: ^16.2.2

  #localization
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/translations/
fonts:
   - family: Nunito
     fonts:
       - asset: assets/Nunito-ExtraLight.ttf
         weight: 200
       - asset: assets/Nunito-Light.ttf
         weight: 300
       - asset: assets/Nunito-Regular.ttf
         weight: 400
       - asset: assets/Nunito-Medium.ttf
         weight: 500
       - asset: assets/Nunito-SemiBold.ttf
         weight: 600
       - asset: assets /Nunito-Bold.ttf
         weight: 700
       - asset: assets/Nunito-ExtraBold.ttf
         weight: 800
       - asset: assets/Nunito-Black.ttf
         weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color_ios: "#F8EEE2"
  adaptive_icon_background: "#F8EEE2"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#F8EEE2"

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#F8EEE2"
  android: true
  ios: true
  web: true