// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqEPGwZHXxoRuoqWRVhZnrogEZavVqlFU',
    appId: '1:24863596152:web:a1bb72fd407a2fd381978d',
    messagingSenderId: '24863596152',
    projectId: 'notely-5e4e9',
    authDomain: 'notely-5e4e9.firebaseapp.com',
    storageBucket: 'notely-5e4e9.firebasestorage.app',
    measurementId: 'G-BZBWRCMVC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_U2_iYCRM3ocv__4Hd8TX-SDwx7dHeo',
    appId: '1:24863596152:android:06fbc73e37c75bce81978d',
    messagingSenderId: '24863596152',
    projectId: 'notely-5e4e9',
    storageBucket: 'notely-5e4e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChETqjm5y5Tp4JpuAWS203iqk4Ob-n_Y8',
    appId: '1:24863596152:ios:86f3d1ce906bba5a81978d',
    messagingSenderId: '24863596152',
    projectId: 'notely-5e4e9',
    storageBucket: 'notely-5e4e9.firebasestorage.app',
    iosBundleId: 'com.example.notely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChETqjm5y5Tp4JpuAWS203iqk4Ob-n_Y8',
    appId: '1:24863596152:ios:86f3d1ce906bba5a81978d',
    messagingSenderId: '24863596152',
    projectId: 'notely-5e4e9',
    storageBucket: 'notely-5e4e9.firebasestorage.app',
    iosBundleId: 'com.example.notely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqEPGwZHXxoRuoqWRVhZnrogEZavVqlFU',
    appId: '1:24863596152:web:a87b19789916e7d881978d',
    messagingSenderId: '24863596152',
    projectId: 'notely-5e4e9',
    authDomain: 'notely-5e4e9.firebaseapp.com',
    storageBucket: 'notely-5e4e9.firebasestorage.app',
    measurementId: 'G-6EGG076DH5',
  );

}