#!/bin/bash
flutter pub run easy_localization:generate -S assets/translations -f keys -o locale_keys.g.dart
flutter pub run easy_localization:generate -S assets/translations
echo -e "// ignore_for_file: constant_identifier_names\n$(cat ./lib/generated/locale_keys.g.dart)" > ./lib/generated/locale_keys.g.dart